version: "3"
services:
  webapp:
    restart: unless-stopped
    # deploy:
    #   restart_policy:
    #     condition: on-failure
    #     delay: 5s
    #     max_attempts: 3
    #     window: 120s
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    labels:
      - "DevelopedBy=Mohamed Zaki"
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
  tests:
    restart: unless-stopped
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    labels:
      - "DevelopedBy=Mohamed Zaki"
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run" , "test"]
